name: Clear Streamlit Cache

on: [push]

jobs:
  clear_cache:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Streamlit
      run: pip install streamlit

    - name: Clear Streamlit Cache
      run: |
        streamlit cache clear
        echo "Streamlit cache cleared"
